commit
racousin/data_science_practice_2024 pull request #13
Opened 2024-09-24 17:39 UTC by manjotgeek17

2024-09-24 17:41 UTC, JulesRob approved these changes

2024-09-24 19:11 UTC, racousin requested changes
The text case should be the same as your usename (ie. without uppercases)

Update user file accordingly and commit your changes

2024-09-24 19:11 UTC, racousin commented on manjotgeek17/module1/user
> +Manjotgeek17,Manjot,Singh
The text case should be the same as your usename (ie. without uppercases)
```suggestion
manjotgeek17,Manjot,Singh
```

2024-11-20 16:55 UTC, racousin commented
I'm closing this PR because no change for a very long time.

2024-11-20 16:55 UTC, closed without merging