Update exercise files
racousin/data_science_practice_2024 pull request #14
Opened 2024-09-24 17:41 UTC by Pollsiesdfi

pull request from your exercise branch to the main branch

2024-10-01 16:55 UTC, ZHAOJiani0326 approved these changes

2024-10-07 12:53 UTC, racousin requested changes
remove the user.txt file

2024-10-08 09:23 UTC, racousin approved these changes
Good work!

2024-10-15 11:48 UTC, racousin approved these changes

2024-10-22 17:41 UTC, merged