Update exercise files
racousin/data_science_practice_2024 pull request #18
Opened 2024-09-24 17:55 UTC by Shuunii1001

pull_request

2024-09-24 18:37 UTC, racousin requested changes

2024-09-24 18:37 UTC, racousin commented on Shuunii/module1/user.txt
> +Shuunii, Shiyi, Wang
You should remove spaces
```suggestion
Shuunii,Shiyi,Wang
```

2024-10-06 08:05 UTC, racousin requested changes
file name should be user. Not user.txt

2024-10-07 12:57 UTC, racousin requested changes
your usernam is Shuunii1001 not Shuunii.

Update the folder-file Shuunii/module1/user.txt to Shuunii1001/module1/user

Update in the file your username from Shuunii,Shiyi,Wang to Shuunii1001,Shiyi,Wang

Commit and push your chnages

2024-10-07 14:03 UTC, Shuunii1001 commented
Dear sir,
I don’t know how to change the name of folder-file and I can’t gitpush after I edited the file.
Best regards,
Wang Shiyi

---- Replied Message ----
| From | Raphael ***@***.***> |
| Date | 10/07/2024 14:58 |
| To | racousin/data_science_practice_2024 ***@***.***> |
| Cc | Shuunii1001 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [racousin/data_science_practice_2024] Update exercise files (PR #18) |

@racousin requested changes on this pull request.

your usernam is Shuunii1001 not Shuunii.

Update the folder-file Shuunii/module1/user.txt to Shuunii1001/module1/user

Update in the file your username from Shuunii,Shiyi,Wang to Shuunii1001,Shiyi,Wang

Commit and push your chnages

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-10-07 19:33 UTC, Shuunii1001 commented
pull_request

2024-10-08 15:57 UTC, closed without merging