My content for module 1 exercises
racousin/data_science_practice_2024 pull request #24
Opened 2024-09-24 19:46 UTC by ZHAOJiani0326

2024-09-24 19:54 UTC, racousin requested changes
you username in file user should be the same as your username ZHAOJiani0326 .
Commit your change and try again.

2024-09-24 19:54 UTC, racousin commented on ZHAOJiani0326/module1/user
> +ZHAO_Jiani,Jiani,ZHAO
```suggestion
ZHAOJiani0326,Jiani,ZHAO
```

2024-09-24 20:15 UTC, ZHAOJiani0326 commented
I have changed the file.

2024-10-01 16:49 UTC, GUOYUDOn approved these changes

2024-10-07 12:56 UTC, racousin commented
Already merged

2024-10-07 21:38 UTC, closed without merging