EXO1
racousin/data_science_practice_2024 pull request #33
Opened 2024-09-30 15:23 UTC by secretpants886

2024-09-30 15:36 UTC, racousin requested changes
rename your folder from Zhan_XU to 
secretpants886 commit and push your changes

2024-10-01 16:20 UTC, JUNKAII reviewed
good

2024-10-01 16:31 UTC, JUNKAII approved these changes
good

2024-10-06 07:51 UTC, racousin approved these changes

2024-10-06 09:14 UTC, merged