Exercise branch3
racousin/data_science_practice_2024 pull request #55
Opened 2024-10-01 17:08 UTC by secretpants886

2024-10-01 17:31 UTC, eloivswild approved these changes

2024-10-06 07:52 UTC, racousin requested changes
remove this file Zhan_XU/module1/user
 you already did it well in https://github.com/racousin/data_science_practice_2024/pull/33/files

2024-10-07 15:43 UTC, racousin requested changes

2024-10-07 15:43 UTC, racousin commented on secretpants886/module2/.DS_Store
remove .DsStore

2024-10-07 17:02 UTC, secretpants886 commented on secretpants886/module2/.DS_Store
It's done sir.

2024-10-07 17:39 UTC, racousin approved these changes
Good work!

2024-10-07 18:25 UTC, merged