Ajout de mon exercice, module 2
racousin/data_science_practice_2024 pull request #56
Opened 2024-10-01 17:14 UTC by chhaoo5

2024-10-06 08:02 UTC, racousin requested changes
in your branch chhaoo5/module2 , remove
- chhaoo5/module2/mysupertools/mysupertools.egg-info/

commit and push your changes. It should be good after that

2024-10-07 11:40 UTC, JulesRob approved these changes

2024-10-08 09:29 UTC, racousin requested changes
remove the

chhaoo5/module2/mysupertools/build/ folder

2024-10-14 15:23 UTC, racousin approved these changes
Well done!

2024-10-14 21:31 UTC, merged